#ifndef MINECRAFTCXX_CLIENT_ENGINE_INCLUDE_ENGINE_MATH_HPP_
#define MINECRAFTCXX_CLIENT_ENGINE_INCLUDE_ENGINE_MATH_HPP_

#include <glm/glm.hpp>

namespace engine {
}

#endif //MINECRAFTCXX_CLIENT_ENGINE_INCLUDE_ENGINE_MATH_HPP_
